##
# @see: https://github.com/alacritty/alacritty-theme/tree/master
#
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
#

import = [
  #  "~/.config/alacritty/themes/themes/gotham.toml"
  #  "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
   "~/.config/alacritty/themes/themes/challenger_deep.toml"
]


##
# @see: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
#
# man 5 alacritty
#


[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Iosevka Term Curly Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly Slab"
style = "Italic"

[font.normal]
family = "Iosevka Term Curly Slab"
style = "Regular"

[font.offset]
x = 1
y = 1

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 6
y = 6


