##
# @see: https://github.com/alacritty/alacritty-theme/tree/master
#
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
#


[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[colors.normal]
black = "0x3B4252"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors.bright]
black = "0x4C566A"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x8FBCBB"
white = "0xECEFF4"


[general]
live_config_reload = true
working_directory = "None"

import = [
  # "~/.config/alacritty/themes/themes/gotham.toml"
    "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
  # "~/.config/alacritty/themes/themes/challenger_deep.toml"
  # "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
  # "~/.config/alacritty/themes/themes/campbell.toml"
  # "~/.config/alacritty/themes/themes/tokyo-night.toml"
  # "~/.config/alacritty/themes/themes/github_dark_tritanopia.toml"
  # "~/.config/alacritty/themes/themes/Cobalt2.toml"
  # "~/.config/alacritty/themes/themes/deep_space.toml"
  # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
  # "~/.config/alacritty/themes/themes/horizon-dark.toml"
  # "~/.config/alacritty/themes/themes/iris.toml"
  # "~/.config/alacritty/themes/themes/iterm.toml"
  # "~/.config/alacritty/themes/themes/xterm.toml"
  # "~/.config/alacritty/themes/themes/material_theme_mod.toml"
  # "~/.config/alacritty/themes/themes/smoooooth.toml"
  # "~/.config/alacritty/themes/themes/terminal_app.toml"
  # "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
  # "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]


##
# @see: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
#
# man 5 alacritty
#


[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[terminal]

shell = { program = "/usr/bin/zsh", args = ["--login",] }
osc52 = "CopyPaste"

[font]
size = 18.0

[font.normal]
family = "Iosevka Term Slab NF"
style = "Regular"

[font.bold]
family = "Iosevka Term Slab NF"
style = "Bold"

[font.italic]
family = "Iosevka Term Slab NF"
style = "Italic"

[font.bold_italic]
family = "Iosevka Term Slab NF"
style = "Bold Italic"


[font.offset]
x = 1
y = 1

[colors]
draw_bold_text_with_bright_colors = true



[window]
dynamic_padding = true
#decorations = "full"
decorations = "none"
startup_mode = "Maximized"

title = "Alacritty@CachyOS"
opacity = 0.8
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3




[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

